[package]
name = "ldap-test-server-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Command line for running OpenLDAP server for testing"
repository.workspace = true
keywords = ["ldap"]
categories = ["command-line-utilities", "development-tools::testing"]

[dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tokio = { version = "1.26.0", features = ["rt-multi-thread", "macros", "signal", "fs"] }
ldap-test-server = { version = "0.0.2", path = "../ldap-test-server" }
clap = { version = "4.1.14", features = ["derive"] }
