[workspace.package]
version = "0.1.0"
authors = ["Mateusz Kondej <m@kondej.net>"]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/mateuszkj/ldap-test-server"

[workspace]
resolver = "2"
members = ["ldap-test-server", "ldap-test-server-cli"]

